import React from 'react'

const LatestNews = () => {
  return (
    <div>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque delectus incidunt impedit dolores culpa, sit aperiam nam! Quod, sunt facilis voluptate id veritatis autem eaque ad explicabo, optio dolor deserunt perspiciatis delectus. Sunt tempora, obcaecati nulla nihil ratione sapiente nemo cum laborum omnis odio commodi dicta! Perspiciatis error possimus rerum voluptas ea! Quis quia, quod iste maiores facilis doloribus assumenda voluptas dolorem quo itaque officia, optio similique accusantium minus quas voluptatem deleniti. Fugiat consequatur repudiandae, sint doloribus dolorum neque tenetur quos, eius repellendus harum voluptas quod quidem autem explicabo tempora? Exercitationem deleniti reiciendis, similique consectetur inventore perspiciatis ea repudiandae repellendus, quam sed temporibus obcaecati laborum libero, id quaerat voluptate voluptatem dignissimos dolor tempora dicta praesentium eveniet dolores rem. Officia qui suscipit aspernatur voluptatum beatae possimus eaque tenetur nihil laborum quae aliquam, repudiandae quas fugit mollitia dignissimos, perferendis praesentium odit vero impedit blanditiis vel facere alias? Necessitatibus consequuntur error porro architecto aperiam explicabo reprehenderit in, dicta dignissimos dolor fuga doloremque autem reiciendis accusamus exercitationem commodi omnis pariatur adipisci! Necessitatibus, sed ab culpa a harum, hic inventore nihil rem veniam dicta fuga, quis perspiciatis repellendus maxime sapiente dolore placeat. Suscipit doloremque voluptatem reprehenderit perspiciatis voluptatibus rem, molestias tempora unde magnam vitae ex.
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque delectus incidunt impedit dolores culpa, sit aperiam nam! Quod, sunt facilis voluptate id veritatis autem eaque ad explicabo, optio dolor deserunt perspiciatis delectus. Sunt tempora, obcaecati nulla nihil ratione sapiente nemo cum laborum omnis odio commodi dicta! Perspiciatis error possimus rerum voluptas ea! Quis quia, quod iste maiores facilis doloribus assumenda voluptas dolorem quo itaque officia, optio similique accusantium minus quas voluptatem deleniti. Fugiat consequatur repudiandae, sint doloribus dolorum neque tenetur quos, eius repellendus harum voluptas quod quidem autem explicabo tempora? Exercitationem deleniti reiciendis, similique consectetur inventore perspiciatis ea repudiandae repellendus, quam sed temporibus obcaecati laborum libero, id quaerat voluptate voluptatem dignissimos dolor tempora dicta praesentium eveniet dolores rem. Officia qui suscipit aspernatur voluptatum beatae possimus eaque tenetur nihil laborum quae aliquam, repudiandae quas fugit mollitia dignissimos, perferendis praesentium odit vero impedit blanditiis vel facere alias? Necessitatibus consequuntur error porro architecto aperiam explicabo reprehenderit in, dicta dignissimos dolor fuga doloremque autem reiciendis accusamus exercitationem commodi omnis pariatur adipisci! Necessitatibus, sed ab culpa a harum, hic inventore nihil rem veniam dicta fuga, quis perspiciatis repellendus maxime sapiente dolore placeat. Suscipit doloremque voluptatem reprehenderit perspiciatis voluptatibus rem, molestias tempora unde magnam vitae ex.
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque delectus incidunt impedit dolores culpa, sit aperiam nam! Quod, sunt facilis voluptate id veritatis autem eaque ad explicabo, optio dolor deserunt perspiciatis delectus. Sunt tempora, obcaecati nulla nihil ratione sapiente nemo cum laborum omnis odio commodi dicta! Perspiciatis error possimus rerum voluptas ea! Quis quia, quod iste maiores facilis doloribus assumenda voluptas dolorem quo itaque officia, optio similique accusantium minus quas voluptatem deleniti. Fugiat consequatur repudiandae, sint doloribus dolorum neque tenetur quos, eius repellendus harum voluptas quod quidem autem explicabo tempora? Exercitationem deleniti reiciendis, similique consectetur inventore perspiciatis ea repudiandae repellendus, quam sed temporibus obcaecati laborum libero, id quaerat voluptate voluptatem dignissimos dolor tempora dicta praesentium eveniet dolores rem. Officia qui suscipit aspernatur voluptatum beatae possimus eaque tenetur nihil laborum quae aliquam, repudiandae quas fugit mollitia dignissimos, perferendis praesentium odit vero impedit blanditiis vel facere alias? Necessitatibus consequuntur error porro architecto aperiam explicabo reprehenderit in, dicta dignissimos dolor fuga doloremque autem reiciendis accusamus exercitationem commodi omnis pariatur adipisci! Necessitatibus, sed ab culpa a harum, hic inventore nihil rem veniam dicta fuga, quis perspiciatis repellendus maxime sapiente dolore placeat. Suscipit doloremque voluptatem reprehenderit perspiciatis voluptatibus rem, molestias tempora unde magnam vitae ex.
    </div>
  )
}

export default LatestNews